ninety_nine_cats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :cats, only: [:index, :show, :new, :edit]
end

ninety_nine_cats/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ninety_nine_cats/app/models/cat.rb
class Cat < ApplicationRecord
  COLORS= [
    'Adi', 
    'Calico', 
    'Blood Red', 
    'Red', 
    'Green'
    ]
  validates :birth_date, :color, :name, :sex, :description, presence: true
  validates :sex, inclusion: { in: ['M', 'F'] }
  validates :color, inclusion: { in: COLORS }
  
  def age
    ((Time.now.to_date - self.birth_date) / 365.25).floor
  end
  
  
end

ninety_nine_cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

ninety_nine_cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  
  def index
    @cats = Cat.all
    # byebug
    render :index
  end
  
  def show
    @cat = Cat.find(params[:id])
    render :show
  end 

  def new
    @cat = Cat.new
    render :new
  end 
  
end

ninety_nine_cats/app/helpers/application_helper.rb
module ApplicationHelper
end

ninety_nine_cats/app/views/cats/edit.html.erb
<form action="<%= edit_cat_url %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <label>
     Name:
     <input type="text" name="cat[name]" value="<%= @cat.name %>">
     <!-- name defines the format in which we send data back to params -->
   </label>
   <br>
   <label>
     Birth Date:
     <input type="date" name="cat[birth_date]" value="<%= @cat.birth_date %>">
   </label>
   <br>
   
   <label>
     Color:
   <select class="" name="cat[color]">
     <option disabled selected>--PLEASE SELECT--</option>
     <% Cat::COLORS.each do |color| %>
     <option value="<%= "#{color}" %>"> <%= "#{color}" %> </option>
     <% end %>
   </select>
   <br>
  </label>
   
   
   
   
   
   <label>
     Sex:
     <br>
     <input type="radio" name="cat[sex]" value="<%= "M"%>">M<br>
     <input type="radio" name="cat[sex]" value="<%= "F"%>">F<br>
   </label>
   <br>
   <br>
   <label>
     Description:
     <br>
     <textarea name="cat[description]" > </textarea>
   </label>
   <br>
   <input type="submit" value="submit value">
</form>

ninety_nine_cats/app/views/cats/index.html.erb
Call the Cats TO ARMS!!!<br>
(meow.) <br>
<ul>
  <% @cats.each do |cat| %>
  <br>
  <li> Name: <%= cat.name %> </li>
  <li> Birth Date: <%= cat.birth_date %> </li>
  <li> Age: <%= cat.age %> </li>
  <li> Color: <%= cat.color %> </li>
  <li> Sex: <%= cat.sex %> </li>
  <li> Description: <%= cat.description %> </li>
  <br>
  <a href='<%= cat_url(cat) %>'>Check out this #coolcat!</a>
  <br>
  <% end %>
  <br>
</ul>

ninety_nine_cats/app/views/cats/new.html.erb
<form>
  <label>
     Name:
     <input type="text" name="cat[name]" value="<%= @cat.name %>">
     <!-- name defines the format in which we send data back to params -->
   </label>
   <br>
   <label>
     Birth Date:
     <input type="date" name="cat[birth_date]" value="<%= @cat.birth_date %>">
   </label>
   <br>
   
   <label>
     Color:
   <select class="" name="cat[color]">
     <option disabled selected>--PLEASE SELECT--</option>
     <% Cat::COLORS.each do |color| %>
     <option value="<%= "#{color}" %>"> <%= "#{color}" %> </option>
     <% end %>
   </select>
   <br>
  </label>
   
   
   
   
   
   <label>
     Sex:
     <br>
     <input type="radio" name="cat[sex]" value="<%= "M"%>">M<br>
     <input type="radio" name="cat[sex]" value="<%= "F"%>">F<br>
   </label>
   <br>
   <br>
   <label>
     Description:
     <br>
     <textarea name="cat[description]" > </textarea>
   </label>
   <br>
   <input type="submit" value="submit value">
</form>

ninety_nine_cats/app/views/cats/show.html.erb
Here is your selected warrior (meow!) 
<br>
<li> Name: <%= @cat.name %> </li>
<li> Birth Date: <%= @cat.birth_date %> </li>
<li> Age: <%= @cat.age %> </li>
<li> Color: <%= @cat.color %> </li>
<li> Sex: <%= @cat.sex %> </li>
<li> Description: <%= @cat.description %> </li>
<br>
<a href="<%= cats_url %>"> See all dem kitties (miao) </a>

ninety_nine_cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NinetyNineCats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>